version: '3.9'

services: 
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=TouchGrassMovies
        
    ports:
      - '5432:5432'